package life.zhk.community.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.ID
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.SENDER
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private Integer sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.RECEIVER
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.TYPE
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.TYPE_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.TITLE_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private String titleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.MAKE_DATE
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private Long makeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.SEND_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private String sendName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.QUESTION_ID
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.STATUS
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.ID
     *
     * @return the value of NOTIFICATION.ID
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.ID
     *
     * @param id the value for NOTIFICATION.ID
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.SENDER
     *
     * @return the value of NOTIFICATION.SENDER
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.SENDER
     *
     * @param sender the value for NOTIFICATION.SENDER
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.RECEIVER
     *
     * @return the value of NOTIFICATION.RECEIVER
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.RECEIVER
     *
     * @param receiver the value for NOTIFICATION.RECEIVER
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.TYPE
     *
     * @return the value of NOTIFICATION.TYPE
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.TYPE
     *
     * @param type the value for NOTIFICATION.TYPE
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.TYPE_NAME
     *
     * @return the value of NOTIFICATION.TYPE_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.TYPE_NAME
     *
     * @param typeName the value for NOTIFICATION.TYPE_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.TITLE_NAME
     *
     * @return the value of NOTIFICATION.TITLE_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public String getTitleName() {
        return titleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.TITLE_NAME
     *
     * @param titleName the value for NOTIFICATION.TITLE_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName == null ? null : titleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.MAKE_DATE
     *
     * @return the value of NOTIFICATION.MAKE_DATE
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public Long getMakeDate() {
        return makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.MAKE_DATE
     *
     * @param makeDate the value for NOTIFICATION.MAKE_DATE
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setMakeDate(Long makeDate) {
        this.makeDate = makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.SEND_NAME
     *
     * @return the value of NOTIFICATION.SEND_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public String getSendName() {
        return sendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.SEND_NAME
     *
     * @param sendName the value for NOTIFICATION.SEND_NAME
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setSendName(String sendName) {
        this.sendName = sendName == null ? null : sendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.QUESTION_ID
     *
     * @return the value of NOTIFICATION.QUESTION_ID
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.QUESTION_ID
     *
     * @param questionId the value for NOTIFICATION.QUESTION_ID
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.STATUS
     *
     * @return the value of NOTIFICATION.STATUS
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.STATUS
     *
     * @param status the value for NOTIFICATION.STATUS
     *
     * @mbg.generated Fri Nov 05 19:57:43 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}